// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_jMoP2pkCY4cnl9hXdFNikp_3WihL3P0',
    appId: '1:176382397:web:d4eae74fbae81893acf2d4',
    messagingSenderId: '176382397',
    projectId: 'flutter-notes-app-fa157',
    authDomain: 'flutter-notes-app-fa157.firebaseapp.com',
    storageBucket: 'flutter-notes-app-fa157.appspot.com',
    measurementId: 'G-R4TQGLN9RF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGvqwkQ_Zv8ARH3CzEpQpDrhSJoD9EvcY',
    appId: '1:176382397:android:d44d5a76fe404662acf2d4',
    messagingSenderId: '176382397',
    projectId: 'flutter-notes-app-fa157',
    storageBucket: 'flutter-notes-app-fa157.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANhSQ_Dz48zqS_p-hgoDnml3YZ7m5lEhs',
    appId: '1:176382397:ios:e76825a09243c3a8acf2d4',
    messagingSenderId: '176382397',
    projectId: 'flutter-notes-app-fa157',
    storageBucket: 'flutter-notes-app-fa157.appspot.com',
    iosClientId: '176382397-8sl4cgai513k90qa5hv8pcq6mp561c45.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANhSQ_Dz48zqS_p-hgoDnml3YZ7m5lEhs',
    appId: '1:176382397:ios:829d0f6675e6a105acf2d4',
    messagingSenderId: '176382397',
    projectId: 'flutter-notes-app-fa157',
    storageBucket: 'flutter-notes-app-fa157.appspot.com',
    iosClientId: '176382397-6grplkb1q0071n3gf3qqcvi7n9ccdn1q.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterNotes.RunnerTests',
  );
}
